# camera device
camera_idx: 0
camera_width: 1920
camera_height: 1080

# checkerboard
checkerboard_rows: 7
checkerboard_cols: 10
checkerboard_box_size_scale : 2.5

# capture option
capture: 15
interval: 100
